/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-09-02 06:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1599025288975L));
    _jspx_dependants.put("/slideMenu.jsp", Long.valueOf(1599025289106L));
    _jspx_dependants.put("/Banner.jsp", Long.valueOf(1599025289575L));
    _jspx_dependants.put("/Title.jsp", Long.valueOf(1599025290059L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/homepage2.css\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/homepage2.css\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"quickmenu\">\r\n");
      out.write("\t\t\t<a href=\"#\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/quick_img_off.png\"\r\n");
      out.write("\t\t\t\talt=\"ê°ë§¹ì  ë¬¸ì\"\r\n");
      out.write("\t\t\t\tonmouseover=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/quick_img_on.png'\"\r\n");
      out.write("\t\t\t\tonmouseout=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/quick_img_off.png'\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("\t<p class=\"text-center\">&copy; WebMarket</p>\r\n");
      out.write("</footer> -->");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/homepage2.css\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"header_in\">\r\n");
      out.write("\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"MainHome.jsp\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo.png\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"menu_list\" id=\"test\">\r\n");
      out.write("\t\t\t\t<ul id=\"menu_main\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">브랜드</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">상품 목록</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">매장</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./Event.jsp\">이벤트/공지사항</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul id=\"menu_sub\">\r\n");
      out.write("\t\t\t\t\t<li>공지사항</li>\r\n");
      out.write("\t\t\t\t\t<li id=\"link_logo\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.facebook.com/GongCha.Korea\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"resources/images/facebook.png\"></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.instagram.com/gongcha.official/\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"resources/images/instargram.png\">\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"store_logo\"><a href=\"#\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"resources/images/sub_menu_logo1.png\"> <span><p>&nbsp&nbsp가맹점</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>전화번호</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>010-1111-1111</p></span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div id=\"hd_name\">\r\n");
      out.write("\t\t\t\t\t<!--슬라이드바  -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"imgs\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/eventpicture.jpg\" />\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"hd_submenu\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"tbl\">\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"./Brand.jsp\">브랜드 소개</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"./products.jsp\">음료</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"./store.jsp\">매장 찾기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"./Event.jsp\">이벤트</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"tbl\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"./products12.jsp\">빙수</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"#\">공지사항</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr id=\"tbl\">\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a href=\"./products13.jsp\">디저트</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/homepage2.css\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\t.container{\r\n");
      out.write("\ttop:100pt;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\t overflow: hidden;\r\n");
      out.write("\twidth: 2500px;\r\n");
      out.write("\theight: 1000px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    left :-240pt;\r\n");
      out.write("    position: ab;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t.carousel-control{\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.carousel-control.left{\r\n");
      out.write("\tleft:190px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.carousel-control.right{\r\n");
      out.write("\r\n");
      out.write("\tright:250px;\r\n");
      out.write("\t}\r\n");
      out.write(".carousel-indicators {\r\n");
      out.write("    bottom: -10px; \r\n");
      out.write("}\r\n");
      out.write("#side_menubar > ul > li {\r\n");
      out.write("margin: 1px;\r\n");
      out.write("float: left;\r\n");
      out.write("}\r\n");
      out.write(".carousel-indicators li{\r\n");
      out.write("box-sizing:border-box;\r\n");
      out.write("border-radius:0;\r\n");
      out.write("text-indent:0;\r\n");
      out.write("line-height: 35pt;\r\n");
      out.write(" background: white;\r\n");
      out.write("}\r\n");
      out.write(".carousel-indicators .active {\r\n");
      out.write("background: indianred;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write(" <!--   <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\">1212</li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\">121</li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\">212</li>\r\n");
      out.write("    </ol> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("      \t<a href=\"#\">\r\n");
      out.write("        \t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner1.jpg\" alt=\"첫 번째 페이지\" style=\"width:100%;\">\r\n");
      out.write("      </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        \t<a href=\"#\">\r\n");
      out.write("        \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner2.jpg\" alt=\"두 번째 페이지\" style=\"width:100%;\">\r\n");
      out.write("</a>\r\n");
      out.write("      </div>\r\n");
      out.write(" \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("      \t<a href=\"#\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner3.jpg\" alt=\"세 번째 페이지\" style=\"width:100%;\">\r\n");
      out.write("     </a>\r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write(" <div class=\"item\">\r\n");
      out.write("      \t<a href=\"#\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/banner3.jpg\" alt=\"네 번째 페이지\" style=\"width:100%;\">\r\n");
      out.write("     </a>\r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id = \"side_menu\">\r\n");
      out.write("  \t<div id = \"side_menubar\">\r\n");
      out.write("\t\t<ul class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\">메뉴1</li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\">메뉴2</li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\">메뉴3</li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"3\">메뉴4</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("<p>dd</p>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/brand.css\"\r\n");
      out.write("\ttype=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\t\t<!-- footer -->\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"footer_inner\">\r\n");
      out.write("\t\t\t\t<div class=\"footer_left\">\r\n");
      out.write("\t\t\t\t\t<img class=\"logo\" src=\"./resources/res_img/ft_logo.png\" alt=\"GONGCHA\">\r\n");
      out.write("\t\t\t\t\t<p class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t(C)GONGCHA KOREA CO.,LTD<br>\r\n");
      out.write("\t\t\t\t\t\tALL RIGHTS RESERVED.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footer_right\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"ft_menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">회사소개</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">제휴/제안</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">이메일무단수집거부</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">사이트맵</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<p class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t고객센터\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tell\">02-779-7758</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"time\">(운영시간 오전 9시~오후 6시/주말 및 공휴일 휴무)</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<address class=\"address\">\r\n");
      out.write("\t\t\t\t\t\t<span>서울 종로구 종로 47(공평동, 7층)</span>\r\n");
      out.write("\t\t\t\t\t\t<span>㈜공차코리아 대표이사 김의열</span>\r\n");
      out.write("\t\t\t\t\t\t<span>사업자등록번호 214-88-84534</span>\r\n");
      out.write("\t\t\t\t\t\t<span>통신판매번호: 2014-서울서초-1322</span>\r\n");
      out.write("\t\t\t\t\t</address>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
